"""empty message

Revision ID: e681f8cbe31a
Revises: 
Create Date: 2023-03-12 19:24:42.453917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e681f8cbe31a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('is_verified', sa.Boolean(create_constraint=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('image_file', sa.String(length=150), nullable=False),
    sa.Column('saved_dogs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('data', sa.String(length=10000), nullable=True),
    sa.Column('image_file', sa.String(length=150), nullable=False),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefered_breed', sa.JSON(), nullable=True),
    sa.Column('prefers_mixed_breed', sa.Boolean(create_constraint=150), nullable=True),
    sa.Column('age_preference', sa.JSON(), nullable=True),
    sa.Column('size_preference', sa.JSON(), nullable=True),
    sa.Column('color_preference', sa.JSON(), nullable=True),
    sa.Column('spay_needed', sa.Boolean(), nullable=True),
    sa.Column('coat_length_preference', sa.String(), nullable=True),
    sa.Column('dog_with_children', sa.Boolean(), nullable=True),
    sa.Column('dog_with_dogs', sa.Boolean(), nullable=True),
    sa.Column('dog_with_cats', sa.Boolean(), nullable=True),
    sa.Column('dog_with_sm_animals', sa.Boolean(), nullable=True),
    sa.Column('dog_with_big_animals', sa.Boolean(), nullable=True),
    sa.Column('dog_in_house', sa.Boolean(), nullable=True),
    sa.Column('yard', sa.Boolean(), nullable=True),
    sa.Column('park', sa.Boolean(), nullable=True),
    sa.Column('activity_level', sa.String(length=150), nullable=True),
    sa.Column('special_need_dog', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_breed', sa.String(length=150), nullable=True),
    sa.Column('mixed_breed', sa.Boolean(), nullable=True),
    sa.Column('age', sa.String(length=150), nullable=True),
    sa.Column('size', sa.String(length=150), nullable=True),
    sa.Column('color', sa.String(length=150), nullable=True),
    sa.Column('spayed', sa.Boolean(), nullable=True),
    sa.Column('coat_length', sa.String(length=150), nullable=True),
    sa.Column('dog_with_children', sa.Boolean(), nullable=True),
    sa.Column('dog_with_dogs', sa.Boolean(), nullable=True),
    sa.Column('dog_with_cats', sa.Boolean(), nullable=True),
    sa.Column('dog_with_sm_animals', sa.Boolean(), nullable=True),
    sa.Column('dog_with_big_animals', sa.Boolean(), nullable=True),
    sa.Column('activity_level', sa.String(length=150), nullable=True),
    sa.Column('special_need_dog', sa.Boolean(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog_info')
    op.drop_table('user_info')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
